### ISSUE TITLE
Accent beats are difficult to tell in dark theme

### ISSUE THREAD

**Issue by FragataIncognita** [patzly/tack-android#32] opened 2024-07-03 17:28 UTC
When the theme is set to dark, the two different beat accent colors become very difficult to tell from eachother.
I would suggest making the dots different shapes or sizes.

Great app also. Thank you very much, soundbrenner has left my phone forever

**Comment by patzly** [comment] 2024-08-01 17:09
The problem is fixed in `v4.2.0` with new outlined styles of the beat indicators!
Thank you so much for the big compliment! Glad to hear that Tack is better than an app by a whole company! :)

**Closed by patzly** 2024-08-01 17:09 UTC
Labels: enhancement
